spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expired-after-minute:
    #     7 days
    access-token: ${JWT_ACCESS_EXPIRED_AFTER_MINUTE:10080}
    #    7 days
    refresh-token: ${JWT_REFRESH_EXPIRED_AFTER_MINUTE:10080}
